(define (amount-to-draw text createTime rate)
  (define currIndex (inexact->exact (floor (* rate (- (time-seconds) createTime)))))
  (substring text 0 (min (string-length text) currIndex))
)

(define maxBufferSize 10)
(define messageBuffer (list))

(define displayMessage (args "alert"))
(define (onMessage key value)
  (if (equal? key "alert")
    (begin
      (set! messageBuffer (reverse (cons (list value (time-seconds)) (reverse messageBuffer)))) 
      (if (> (length messageBuffer) maxBufferSize)
        (set! messageBuffer (cdr messageBuffer))
      )
      (format #t "list is: ~a\n" messageBuffer)
    )
  )
  (if (equal? key "enemyhit")
    (format #t "show hitmaker\n")
  )
  (if (equal? key displayMessage) 
    (onMessage "alert" (string-append "message: " key value))
  )
  (if (equal? key "velocity") (set-speed value))
)

(define (render-alerts yoffset buffer)
  (if (> (length buffer) 0)
    (begin
      (draw-text (amount-to-draw (car (car buffer)) (cadr (car buffer)) 100) 50 yoffset 4)
      (render-alerts (+ yoffset 10) (cdr buffer))
    )
  )
)

(define showspeed (args "speed"))
(define speed 0)
(define (set-speed velocityStr) 
  (define vel (map string->number (string-split velocityStr #\ )))
  (define xvel (car vel))
  (define yvel (cadr vel))
  (define zvel (caddr vel))
  (define speedvel (sqrt (+ (* xvel xvel) (* yvel yvel) (* zvel zvel))))
  (set! speed speedvel)
  (format #t "speed ~a\n" speedvel)
)
(define (onFrame)
  (render-alerts 400 messageBuffer)
  (if showspeed (draw-text (string-append "SPEED:" (number->string (round speed))) 50 900 5))
)

(define crosshairobjname "crosshair")
(define (set-crosshair image)
  (format #t "placeholder set crosshair: ~a\n" image)
  (gameobj-setattr! 
    (lsobj-name "crosshair")
    (list
      (list "texture" image)
    )
  )
)
(define crosshair (args "crosshair"))
(if (string? crosshair) 
  (set-crosshair crosshair)
)
