(define lastTime (time-seconds))
(define elapsedTime 0)

(define movement-speed 0.1)
(define (set-movement-speed speed)
  (set! movement-speed speed)
  (display (string-append "traits: setting speed: " (number->string speed) "\n"))
)

(define configIndex 0)
(define (nextConfigIndex) (set! configIndex (+ configIndex 1)))
(define (prevConfigIndex) (set! configIndex (max 0 (- configIndex 1))))
(define (update-config)
  (define traits (sql (sql-compile "select movement-speed from traits")))
  (if (= (length traits) 0)
    (display "no traits in config\n")
    (if (>= configIndex (length traits))
      (set! configIndex (max 0 (- (length traits) 1)))
      (let ((targettrait (list-ref traits configIndex)))
        (display (string-append "Settings config to index: " (number->string configIndex) "\n"))
        (set-movement-speed (string->number (list-ref targettrait 0)))
      )
    )
  )
)


(define (onKey key scancode action mods) 
  (if (= key 87)
    (begin 
      (if (= action 1) (set! go-forward #t))
      (if (= action 0) (set! go-forward #f))
    )
  )
  (if (= key 65)
    (begin
      (if (= action 1) (set! go-left #t))
      (if (= action 0) (set! go-left #f))
    )
  )
  (if (= key 83)
    (begin
      (if (= action 1) (set! go-backward #t))
      (if (= action 0) (set! go-backward #f))
    )
  )
  (if (= key 68)
    (begin
      (if (= action 1) (set! go-right #t))
      (if (= action 0) (set! go-right #f))
    )
  )
  (if (and (= key 264) (= action 1)) (nextConfigIndex)) ; down arrow
  (if (and (= key 265) (= action 1)) (prevConfigIndex)) ; up arrow
  (if (and (= key 345) (= action 1)) (update-config))   ; right ctrl
)

(define (move x y z) 
  (display "move placeholder: ")
  (display x) (display " ")
  (display y) (display " ")
  (display z) (display "\n")
  (applyimpulse-rel mainobj (list x y z))
)

(define go-forward #f)
(define go-left #f)
(define go-backward #f)
(define go-right #f)
(define (onFrame)
  (define currTime (time-seconds))
  (set! elapsedTime (- currTime lastTime))
  (set! lastTime currTime)
  (if (equal? go-forward  #t) (move 0 0 (* -1 movement-speed)))
  (if (equal? go-left     #t) (move (* -0.8 movement-speed) 0 0))
  (if (equal? go-right    #t) (move (* 0.8 movement-speed) 0 0))
  (if (equal? go-backward #t) (move 0 0 movement-speed))
)
