# 
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.synced_folder "../../../", "/arcade", type: "nfs", nfs_version: 4

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 8192
    libvirt.cpus = 4
    libvirt.video_type = "virtio"
    libvirt.sound_type = "ich9"


  end

  config.vm.provision "shell", path: "setup.sh"
end